/* eslint-disable import/no-anonymous-default-export */
export default [
  {
    TT: true,
    Day: "MON", // true denotes schedule 1 where there is a class from 9-10 and another class from 10-11 in the morning
    Period1: "DAA",
    Period2: "MES",
    Period3: "MAT41",
    Period4: "OS",
    Period5: "MAT41",
    Period6: "DIPMAT",
    Period7: "DIPMAT",
  },
  {
    TT: false,
    Day: "TUE", // false denotes schedule 2 where there is a class from 9-11:30 in the morning
    Period1: "DAA Lab/ MES Lab/ PP Lab",
    Period2: "DAA Lab/ MES Lab/ PP Lab",
    Period3: "MAT41",
    Period4: "UHV",
    Period5: "-",
    Period6: "-",
    // Period7: "-",  // no period 7 on schedule 2
  },
  {
    TT: true,
    Day: "WED",
    Period1: "-",
    Period2: "OS",
    Period3: "DAA",
    Period4: "MES",
    Period5: "BFE",
    Period6: "DIPMAT",
    Period7: "DIPMAT",
  },
  {
    TT: true,
    Day: "THU",
    Period1: "DAA Lab/ MES Lab/ PP Lab",
    Period2: "DAA Lab/ MES Lab/ PP Lab",
    Period3: "OS",
    Period4: "AE",
    Period5: "DAA Lab/ MES Lab/ PP Lab",
    Period6: "DAA Lab/ MES Lab/ PP Lab",
    Period7: "-",
  },
  {
    TT: true,
    Day: "FRI",
    Period1: "MAT41",
    Period2: "OS",
    Period3: "CIP",
    Period4: "DAA",
    Period5: "DAA Lab/ MES Lab/ PP Lab",
    Period6: "DAA Lab/ MES Lab/ PP Lab",
    Period7: "-",
  },
  {
    TT: true,
    Day: "SAT",
    Period1: "-",
    Period2: "-",
    Period3: "-",
    Period4: "-",
    Period5: "-",
    Period6: "-",
    Period7: "-",
  },
];
