/* eslint-disable import/no-anonymous-default-export */
export default [
  {
    sName: "ABHIJAT DAKSHESH",
    sUSN: "1RF21IS001",
    Present: true,
    Batch: 1,
  },
  {
    sName: "ABHISHEK PANDEY",
    sUSN: "1RF21IS002",
    Present: true,
    Batch: 1,
  },
  {
    sName: "ABHISHEK SHRIDHAR HEGDE",
    sUSN: "1RF21IS004",
    Present: true,
    Batch: 1,
  },
  {
    sName: "ABHYUDITH M BHARADHWAJ",
    sUSN: "1RF21IS005",
    Present: true,
    Batch: 1,
  },
  {
    sName: "ADITYA SARASWAT",
    sUSN: "1RF21IS006",
    Present: true,
    Batch: 1,
  },
  {
    sName: "ANIRUDH MADHUSUDAN BALGI",
    sUSN: "1RF21IS007",
    Present: true,
    Batch: 1,
  },
  {
    sName: "ANIRUDH S CHAKRAPANI",
    sUSN: "1RF21IS008",
    Present: true,
    Batch: 1,
  },
  {
    sName: "ANKIT RAJ",
    sUSN: "1RF21IS009",
    Present: true,
    Batch: 1,
  },
  {
    sName: "ANURAG PATIL",
    sUSN: "1RF21IS010",
    Present: true,
    Batch: 1,
  },
  {
    sName: "AVIKSHITHA S SHARMA",
    sUSN: "1RF21IS011",
    Present: true,
    Batch: 1,
  },
  {
    sName: "AYUSH KESHARI",
    sUSN: "1RF21IS012",
    Present: true,
    Batch: 1,
  },
  {
    sName: "BENAKA K B",
    sUSN: "1RF21IS013",
    Present: true,
    Batch: 1,
  },
  {
    sName: "BRUNDA.R",
    sUSN: "1RF21IS016",
    Present: true,
    Batch: 1,
  },
  {
    sName: "CHARITHA K RAJ",
    sUSN: "1RF21IS017",
    Present: true,
    Batch: 1,
  },
  {
    sName: "CHIRAG M N",
    sUSN: "1RF21IS018",
    Present: true,
    Batch: 1,
  },
  {
    sName: "CHIRANTH R RAICHUR",
    sUSN: "1RF21IS019",
    Present: true,
    Batch: 1,
  },
  {
    sName: "DARSHAN GOWDA S R",
    sUSN: "1RF21IS020",
    Present: true,
    Batch: 1,
  },
  {
    sName: "DHANUSHREE M S",
    sUSN: "1RF21IS021",
    Present: true,
    Batch: 1,
  },
  {
    sName: "DHANYA VENKATRAMAN HEGDE",
    sUSN: "1RF21IS022",
    Present: true,
    Batch: 1,
  },
  {
    sName: "EZEKIEL DAVID",
    sUSN: "1RF21IS023",
    Present: true,
    Batch: 1,
  },
  {
    sName: "JASHWANTH.M.S",
    sUSN: "1RF21IS026",
    Present: true,
    Batch: 1,
  },
  {
    sName: "KAVYA H M",
    sUSN: "1RF21IS027",
    Present: true,
    Batch: 1,
  },
  {
    sName: "KEMTHUR SURAJ",
    sUSN: "1RF21IS028",
    Present: true,
    Batch: 1,
  },
  {
    sName: "KETHESH K",
    sUSN: "1RF21IS029",
    Present: true,
    Batch: 2,
  },
  {
    sName: "KHYATHI REDDY P",
    sUSN: "1RF21IS030",
    Present: true,
    Batch: 2,
  },
  {
    sName: "LOCHAN.R",
    sUSN: "1RF21IS031",
    Present: true,
    Batch: 2,
  },
  {
    sName: "MADHUSHREE C S",
    sUSN: "1RF21IS032",
    Present: true,
    Batch: 2,
  },
  {
    sName: "MAYANK SHARMA",
    sUSN: "1RF21IS033",
    Present: true,
    Batch: 2,
  },
  {
    sName: "MOHINI SAHA",
    sUSN: "1RF21IS034",
    Present: true,
    Batch: 2,
  },
  {
    sName: "NIHAL S SETTY",
    sUSN: "1RF21IS035",
    Present: true,
    Batch: 2,
  },
  {
    sName: "PAVAN KRISHNA.K",
    sUSN: "1RF21IS036",
    Present: true,
    Batch: 2,
  },
  {
    sName: "PRAJWAL.K",
    sUSN: "1RF21IS037",
    Present: true,
    Batch: 2,
  },
  {
    sName: "PRANESWARA V",
    sUSN: "1RF21IS038",
    Present: true,
    Batch: 2,
  },
  {
    sName: "PRARTHANA. N. AITHAL",
    sUSN: "1RF21IS039",
    Present: true,
    Batch: 2,
  },
  {
    sName: "PRITHVI P SHENOY",
    sUSN: "1RF21IS040",
    Present: true,
    Batch: 2,
  },
  {
    sName: "RAHUL HARISH",
    sUSN: "1RF21IS041",
    Present: true,
    Batch: 2,
  },
  {
    sName: "REDDY CHARITHA NOOLU",
    sUSN: "1RF21IS042",
    Present: true,
    Batch: 2,
  },
  {
    sName: "ROHITH GOWDA",
    sUSN: "1RF21IS043",
    Present: true,
    Batch: 2,
  },
  {
    sName: "S HARINI",
    sUSN: "1RF21IS044",
    Present: true,
    Batch: 2,
  },
  {
    sName: "SAKSHI M",
    sUSN: "1RF21IS045",
    Present: true,
    Batch: 2,
  },
  {
    sName: "SANJANA A",
    sUSN: "1RF21IS046",
    Present: true,
    Batch: 2,
  },
  {
    sName: "SARAH RUKHMUDDIN RAJGOLI",
    sUSN: "1RF21IS047",
    Present: true,
    Batch: 2,
  },
  {
    sName: "SAYEEDA BAQT",
    sUSN: "1RF21IS048",
    Present: true,
    Batch: 2,
  },
  {
    sName: "SHASHANK S RAO",
    sUSN: "1RF21IS049",
    Present: true,
    Batch: 2,
  },
  {
    sName: "SHIVANGI SINGH",
    sUSN: "1RF21IS051",
    Present: true,
    Batch: 2,
  },
  {
    sName: "SHOWGHI R B K",
    sUSN: "1RF21IS052",
    Present: true,
    Batch: 3,
  },
  {
    sName: "SHREYAS MONTADKA",
    sUSN: "1RF21IS053",
    Present: true,
    Batch: 3,
  },
  {
    sName: "SRIVATSA HS",
    sUSN: "1RF21IS054",
    Present: true,
    Batch: 3,
  },
  {
    sName: "TEJAS HEGDE",
    sUSN: "1RF21IS055",
    Present: true,
    Batch: 3,
  },
  {
    sName: "UTHPALA V S",
    sUSN: "1RF21IS056",
    Present: true,
    Batch: 3,
  },
  {
    sName: "VARUN SANJEEV NALDURGKAR",
    sUSN: "1RF21IS057",
    Present: true,
    Batch: 3,
  },
  {
    sName: "VEDASHREE B",
    sUSN: "1RF21IS058",
    Present: true,
    Batch: 3,
  },
  {
    sName: "VEDIKA TEJA SRIVATSA",
    sUSN: "1RF21IS059",
    Present: true,
    Batch: 3,
  },
  {
    sName: "VISHRUTH DEV",
    sUSN: "1RF21IS060",
    Present: true,
    Batch: 3,
  },
  {
    sName: "VIVEK MANJUNATH NAIK",
    sUSN: "1RF21IS061",
    Present: true,
    Batch: 3,
  },
  {
    sName: "Y NAGAVAMSI",
    sUSN: "1RF21IS062",
    Present: true,
    Batch: 3,
  },
  {
    sName: "HARINI YALIPI",
    sUSN: "1RF21IS063",
    Present: true,
    Batch: 3,
  },
  {
    sName: "DIVYA MALLIKARJUNA",
    sUSN: "1RF21IS064",
    Present: true,
    Batch: 3,
  },
  {
    sName: "VIJAY KUMAR GOWDA K K",
    sUSN: "1RF21IS065",
    Present: true,
    Batch: 3,
  },
  {
    sName: "KENNETH OSWIN",
    sUSN: "1RF21IS066",
    Present: true,
    Batch: 3,
  },
  {
    sName: "AMRIT S",
    sUSN: "1RF21IS067",
    Present: true,
    Batch: 3,
  },
  {
    sName: "ANAISHA SHARMA",
    sUSN: "1RF21IS068",
    Present: true,
    Batch: 3,
  },
  {
    sName: "DUSHYANTH R BEELAGI",
    sUSN: "1RF22IS400",
    Present: true,
    Batch: 3,
    Dip: true,
  },
  {
    sName: "MALLIKARJUN",
    sUSN: "1RF22IS401",
    Present: true,
    Batch: 3,
    Dip: true,
  },
  {
    sName: "NITHIN V",
    sUSN: "1RF22IS402",
    Present: true,
    Batch: 3,
    Dip: true,
  },
  {
    sName: "HARISH R",
    sUSN: "1RF22IS403",
    Present: true,
    Batch: 3,
    Dip: true,
  },
  {
    sName: "PRIYANKA M",
    sUSN: "1RF22IS404",
    Present: true,
    Batch: 3,
    Dip: true,
  },
];
