/* eslint-disable import/no-anonymous-default-export */
export default [
    {
      Subject: "Mathematical Foundations forComputing (21CS41)",
      abbriviation: "MAT41",
      StaffName: "Dr.Sivasankar",
      GoogleClassroom: "",
      GoogleSite: "",
    },
    {
      Subject: "Design and Analysis of Algorithms(21CS42)",
      abbriviation: "DAA",
      StaffName: "Prof. DEEPAK D.J(DDJ)",
      GoogleClassroom: "",
      GoogleSite: "",
    },
    {
      Subject: "Microcontroller and EmbeddedSystems (21CS43)",
      abbriviation: "MES",
      StaffName: "Dr. NIHARIKA P KUMAR(NPK)",
      GoogleClassroom: "",
      GoogleSite: "",
    },
    {
      Subject: "Operating System (21CS44 ) ",
      abbriviation: "OS",
      StaffName: "Dr. LATHA C A (LCA) ",
      GoogleClassroom: "",
      GoogleSite: "",
    },
    {
      Subject: "Biology For Engineers (21BE45)",
      abbriviation: "BFE",
      StaffName: "New Faculty",
      GoogleClassroom: "",
      GoogleSite: "",
    },
    {
      Subject: "Python Programming Laboratory(21CSL46)",
      abbriviation: "PP Lab",
      StaffName: "AA,SD,KK",
      GoogleClassroom: "",
      GoogleSite: "",
    },
    // {
    //   Subject: "Design and Analysis of AlgorithmLaboratory (18CSL47)",
    //   abbriviation: "DAA Lab",
    //   StaffName: "DDJ,LCA,KK",
    //   GoogleClassroom: "",
    //   GoogleSite: "",
    // },
    // {
    //   Subject: "Microcontroller and Embedded SystemsLaboratory (18CSL48)",
    //   abbriviation: "MES Lab",
    //   StaffName: "NPK,SD",
    //   GoogleClassroom: "",
    //   GoogleSite: "",
    // },
    {
      Subject: "Constitution of India & ProfessionalEthics (21CIP47)",
      abbriviation: "CIP",
      StaffName: "External Faculty",
      GoogleClassroom: "",
      GoogleSite: "",
    },
    {
      Subject: "Ability Enhancement Course- IV--UnixShell Programming (21CS482)",
      abbriviation: "AE",
      StaffName: "SP",
      GoogleClassroom: "",
      GoogleSite: "",
    },
    {
      Subject: "Universal Human Values (21UH49)",
      abbriviation: "UHV",
      StaffName: "Mr.Thejas",
      GoogleClassroom: "",
      GoogleSite: "",
    },
    {
      Subject: "Additional Mathematics - II (21MATDIP41)",
      abbriviation: "DIPMAT",
      StaffName: "Dr.Nagabhushan",
      GoogleClassroom: "",
      GoogleSite: "",
    },
  ];